# Please set 'QIITA_TOKEN' secret to your repository
name: Publish articles

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update image paths for each article
        run: |
          # 記事ファイル(.md)をループ処理
          find public -name "*.md" | while read -r md_file; do
            # 記事名を取得 (例: public/article1.md -> article1)
            article_name=$(basename "$md_file" .md)
            
            # 記事内の相対パス(../images/article1/...) をGitHubの公開URLへ置換
            sed -i "s|(\../images/$article_name/| (https://raw.githubusercontent.com/hiro-murakami/qiita-content/main/images/$article_name/|g" "$md_file"
          done

      - uses: increments/qiita-cli/actions/publish@v1
        with:
          qiita-token: ${{ secrets.QIITA_TOKEN }}
          root: "."
